# Generated by Django 3.2 on 2024-09-27 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(default='artwork description')),
                ('image', models.ImageField(upload_to='img/artwork')),
                ('rating', models.FloatField(default=3.0)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(default='Author description', max_length=300)),
                ('rating', models.FloatField(default=3.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='id',
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(default='gallery description'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='rating',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='gallery',
            name='visitor_capacity',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_name',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='StyleTag',
            fields=[
                ('tag_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(default='styletag description')),
                ('artwork', models.ManyToManyField(related_name='styletag', to='core.Artwork')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('order_date', models.DateField()),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='core.gallery')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork', to='core.author'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork', to='core.gallery'),
        ),
    ]
