# Generated by Django 3.2 on 2024-09-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240926_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='year',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
