# Generated by Django 3.2 on 2024-10-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_artwork_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='img/gallery/default.jpg', upload_to='img/gallery'),
        ),
    ]
