# Generated by Django 3.2 on 2024-10-27 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_comment_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.FloatField(blank=True, default=3.0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default="the user hasn't made comment"),
        ),
    ]
