# Generated by Django 3.2 on 2024-10-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20241027_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(editable=False, max_length=350, primary_key=True, serialize=False),
        ),
    ]
